[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "MegaPiggy"
name = "EnumUtils"
description = "A library to help with creating and getting Enums"
websiteUrl = "https://github.com/MegaPiggy/LethalCompanyEnumUtils"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "Build"

[[build.copy]]
source = "Build/LCEnumUtils.dll"
target = "/"

[[build.copy]]
source = "Build/LCEnumUtils.xml"
target = "/"

[[build.copy]]
source = "CHANGELOG.md"
target = "/"

[[build.copy]]
source = "LICENSE"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "mods", "libraries", "bepinex", "tools", ]


